Repository sosow0212/2024-pop-cloud, pull requests merged in 2024-09, with the labels that each got.

#29 feat: Popups, Recommend의 캐싱 작업 및 배치 스케줄러 추가
  backend/pcloud-api/docs/asciidoc/recommends.adoc
  backend/pcloud-api/src/main/java/com/api/show/common/annotation/ClientIpFinder.java
  backend/pcloud-api/src/main/java/com/api/show/common/config/ShowCommonHandlerMethodArgumentResolverConfig.java
  backend/pcloud-api/src/main/java/com/api/show/common/resolver/ClientIpFinderResolver.java
  backend/pcloud-api/src/main/java/com/api/show/popups/application/PopupsEventHandler.java
  backend/pcloud-api/src/main/java/com/api/show/popups/application/PopupsQueryService.java
  backend/pcloud-api/src/main/java/com/api/show/popups/infrastructure/PopupsCacheRepositoryImpl.java
  backend/pcloud-api/src/main/java/com/api/show/popups/presentation/PopupsController.java
  backend/pcloud-api/src/main/java/com/api/show/recommend/application/RecommendService.java
  backend/pcloud-api/src/main/java/com/api/show/recommend/infrastructure/RecommendRepositoryImpl.java
  backend/pcloud-api/src/main/java/com/api/show/recommend/presentation/RecommendController.java
  backend/pcloud-api/src/main/java/com/api/show/recommend/presentation/resolver/PopularShowRequestArgumentResolver.java
  backend/pcloud-api/src/test/java/com/api/helper/MockBeanInjection.java
  backend/pcloud-api/src/test/java/com/api/show/popups/application/PopupsServiceConcurrencyTest.java
  backend/pcloud-api/src/test/java/com/api/show/popups/presentation/PopupsControllerWebMvcTest.java
  backend/pcloud-api/src/test/java/com/api/show/recommend/application/RecommendServiceTest.java
  backend/pcloud-api/src/test/java/com/api/show/recommend/infrastructure/RecommendQueryRepositoryTest.java
  backend/pcloud-api/src/test/java/com/api/show/recommend/presentation/RecommendControllerWebMvcTest.java
  backend/pcloud-batch/src/main/java/com/batch/annotation/BatchPublisher.java
  backend/pcloud-batch/src/main/java/com/batch/annotation/BatchService.java
  backend/pcloud-batch/src/main/java/com/batch/global/common/event/BatchEvent.java
  backend/pcloud-batch/src/main/java/com/batch/global/config/AsyncConfig.java
  backend/pcloud-batch/src/main/java/com/batch/global/config/RestTemplateConfig.java
  backend/pcloud-batch/src/main/java/com/batch/global/config/ScheduleConfig.java
  backend/pcloud-batch/src/main/java/com/batch/global/config/SlackAppender.java
  backend/pcloud-batch/src/main/java/com/batch/global/config/moduleutils/ComponentScanConfig.java
  backend/pcloud-batch/src/main/java/com/batch/global/config/moduleutils/PropertySourceScanConfig.java
  backend/pcloud-batch/src/main/java/com/batch/global/config/moduleutils/YamlPropertySourceFactory.java
  backend/pcloud-batch/src/main/java/com/batch/job/show/popups/application/PopupsBatchPublisher.java
  backend/pcloud-batch/src/main/java/com/batch/job/show/popups/application/PopupsBatchService.java
  backend/pcloud-batch/src/main/java/com/batch/job/show/popups/application/event/ClearedIpEvent.java
  backend/pcloud-batch/src/main/java/com/batch/job/show/popups/domain/PopupsCacheBatchRepository.java
  backend/pcloud-batch/src/main/java/com/batch/job/show/popups/infrastructure/PopupsCacheBatchRepositoryImpl.java
  backend/pcloud-batch/src/main/java/com/batch/job/show/recommend/application/RecommendBatchPublisher.java
  backend/pcloud-batch/src/main/java/com/batch/job/show/recommend/application/RecommendBatchService.java
  backend/pcloud-batch/src/main/java/com/batch/job/show/recommend/application/event/ClearedRecommendEvent.java
  backend/pcloud-batch/src/main/java/com/batch/job/show/recommend/domain/RecommendCacheBatchRepository.java
  backend/pcloud-batch/src/main/java/com/batch/job/show/recommend/infrastructure/RecommendCacheBatchRepositoryImpl.java
  backend/pcloud-batch/src/main/resources/logback-spring.xml
  backend/pcloud-domain/src/main/java/com/domain/show/popups/cache/PopupsCacheRepository.java
  backend/pcloud-domain/src/main/java/com/domain/show/popups/event/PopupsFoundEvent.java
  backend/pcloud-domain/src/main/java/com/domain/show/recommend/domain/Recommend.java
  backend/pcloud-domain/src/main/java/com/domain/show/recommend/domain/Recommends.java
  backend/pcloud-domain/src/main/java/com/domain/show/recommend/domain/dto/RecommendSimpleResponse.java
  backend/pcloud-domain/src/main/java/com/domain/show/recommend/infrastructure/RecommendQueryRepository.java
  backend/pcloud-domain/src/test/java/com/domain/show/recommend/domain/RecommendsTest.java
  backend/pcloud-infrastructure/build.gradle
  backend/pcloud-infrastructure/src/main/java/com/infra/config/RedisCacheConfig.java
  backend/pcloud-infrastructure/src/main/java/com/infra/config/RedisConfig.java
  backend/pcloud-infrastructure/src/main/java/com/infrastructure/PCloudInfraApplication.java
  backend/pcloud-infrastructure/src/main/java/com/infrastructure/config/RedisCacheConfig.java
  backend/pcloud-infrastructure/src/main/java/com/infrastructure/config/RedisConfig.java
  backend/pcloud-infrastructure/src/test/java/com/infrastructure/PCloudInfraApplicationTest.java
  backend/pcloud-infrastructure/src/test/java/com/infrastructure/study/redis/RedisTemplateTest.java
Labels: feat, 성능개선

#33 feat: exhibition의 캐싱 작업과 배치 작업을 진행한다
  backend/pcloud-api/src/main/java/com/api/show/exhibition/application/ExhibitionEventHandler.java
  backend/pcloud-api/src/main/java/com/api/show/exhibition/application/ExhibitionQueryService.java
  backend/pcloud-api/src/main/java/com/api/show/exhibition/infrastructure/ExhibitionCacheRepositoryImpl.java
  backend/pcloud-api/src/main/java/com/api/show/exhibition/presentation/ExhibitionController.java
  backend/pcloud-api/src/test/java/com/api/show/exhibition/application/ExhibitionQueryServiceTest.java
  backend/pcloud-api/src/test/java/com/api/show/exhibition/presentation/ExhibitionControllerWebMvcTest.java
  backend/pcloud-batch/src/main/java/com/batch/job/show/exhibition/application/ExhibitionBatchPublisher.java
  backend/pcloud-batch/src/main/java/com/batch/job/show/exhibition/application/ExhibitionBatchService.java
  backend/pcloud-batch/src/main/java/com/batch/job/show/exhibition/application/event/ClearedExhibitionIpEvent.java
  backend/pcloud-batch/src/main/java/com/batch/job/show/exhibition/domain/ExhibitionCacheBatchRepository.java
  backend/pcloud-batch/src/main/java/com/batch/job/show/exhibition/infrasturcture/ExhibitionCacheBatchRepositoryImpl.java
  backend/pcloud-domain/src/main/java/com/domain/show/exhibition/cache/ExhibitionCacheRepository.java
  backend/pcloud-domain/src/main/java/com/domain/show/exhibition/domain/Exhibition.java
  backend/pcloud-domain/src/main/java/com/domain/show/exhibition/domain/ExhibitionRepository.java
  backend/pcloud-domain/src/main/java/com/domain/show/exhibition/event/ExhibitionFoundEvent.java
  backend/pcloud-domain/src/main/java/com/domain/show/exhibition/infrastructure/ExhibitionJpaRepository.java
  backend/pcloud-domain/src/main/java/com/domain/show/exhibition/infrastructure/ExhibitionRepositoryImpl.java
  backend/pcloud-domain/src/testFixtures/java/show/exhibition/infrasturcture/ExhibitionFakeRepository.java
Labels: feat

#35 feat/34: frontend 초기세팅
  .gitignore
  frontend/.commitlintrc.json
  frontend/.eslintrc.json
  frontend/.gitignore
  frontend/.husky/commit-msg
  frontend/.husky/pre-commit
  frontend/.husky/pre-push
  frontend/.prettierrc
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/.vscode/settings.json
  frontend/README.md
  frontend/components.json
  frontend/next.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/postcss.config.mjs
  frontend/public/icons/.gitkeep
  frontend/public/images/.gitkeep
  frontend/src/api/.gitkeep
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/page.tsx
  frontend/src/components/common/index.ts
  frontend/src/constants/.gitkeep
  frontend/src/hooks/index.ts
  frontend/src/store/.gitkeep
  frontend/src/stories/.gitkeep
  frontend/src/types/.gitkeep
  frontend/src/utils/index.ts
  frontend/tailwind.config.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: FE

#41 feat: 스토리북 자동배포 설정
  .github/workflows/storybook.yml
  frontend/.storybook/main.ts
  frontend/.storybook/preview.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/common/button/index.stories.tsx
  frontend/src/components/common/button/index.tsx
  frontend/src/components/common/list-card/index.tsx
  frontend/src/stories/intro.mdx
Labels: feat, FE

#50 fix: 절대경로 탐지 오류 수정
  frontend/tsconfig.json
Labels: fix, FE

#47 feat: 팝업리스트 카드 컴포넌트 제작
  frontend/global.d.ts
  frontend/next.config.mjs
  frontend/package.json
  frontend/public/images/luffi.jpg
  frontend/src/components/common/like-button/index.stories.tsx
  frontend/src/components/common/like-button/index.tsx
  frontend/src/components/common/list-card/index.stories.tsx
  frontend/src/components/common/list-card/index.tsx
  frontend/tailwind.config.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: feat, FE

#56 feat/52 msw 기본설정
  frontend/.env.development
  frontend/.eslintignore
  frontend/.eslintrc.json
  frontend/next.config.mjs
  frontend/package.json
  frontend/public/mockServiceWorker.js
  frontend/src/app/layout.tsx
  frontend/src/components/common/like-button/index.stories.tsx
  frontend/src/components/common/like-button/index.tsx
  frontend/src/components/common/list-card/index.stories.tsx
  frontend/src/components/common/list-card/index.tsx
  frontend/src/components/mobile-size-watcher/index.ts
  frontend/src/components/modal/alert-dialog.tsx
  frontend/src/components/modal/index.stories.tsx
  frontend/src/components/modal/login-modal.tsx
  frontend/src/components/modal/modal-container.tsx
  frontend/src/components/nav-bar/index.tsx
  frontend/src/components/ui/cn.ts
  frontend/src/components/ui/dialog.tsx
  frontend/src/components/ui/drawer.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/dummy.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/http.ts
  frontend/tailwind.config.ts
  frontend/yarn.lock
Labels: feat, fix, FE

#53 feat: 캐러셀 컴포넌트를 제작한다
  frontend/package-lock.json
  frontend/package.json
  frontend/public/images/.gitkeep
  frontend/public/images/mock.jpeg
  frontend/public/images/mock2.jpeg
  frontend/public/images/mock3.jpeg
  frontend/src/app/globals.css
  frontend/src/components/common/carousel/index.stories.tsx
  frontend/src/components/common/carousel/index.tsx
  frontend/src/components/modal/index.stories.tsx
  frontend/src/components/modal/login-modal.tsx
  frontend/src/components/modal/modal-container.tsx
  frontend/src/components/ui/button.tsx
  frontend/src/components/ui/carousel.tsx
  frontend/src/components/ui/cn.ts
  frontend/src/components/ui/drawer.tsx
  frontend/yarn.lock
Labels: feat, FE

#58 Feat: 네비게이션 바 제작한다
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/components/mobile-header/_components/back-button.tsx
  frontend/src/components/mobile-header/_components/header-content.tsx
  frontend/src/components/mobile-header/index.tsx
  frontend/src/components/nav-bar/_components/nav-icon-button.tsx
  frontend/src/components/nav-bar/_components/nav-logo.tsx
  frontend/src/components/nav-bar/_components/nav-menu.tsx
  frontend/src/components/nav-bar/bottom-nav/index.tsx
  frontend/src/components/nav-bar/index.tsx
  frontend/src/components/nav-bar/side-nav/index.tsx
Labels: feat, FE

#65 feat: Popups 단건 캐싱 및 Evict와 동시성 문제 발생 해결
  backend/pcloud-api/docs/asciidoc/index.adoc
  backend/pcloud-api/src/main/java/com/api/show/popups/application/PopupsQueryService.java
  backend/pcloud-api/src/main/java/com/api/show/popups/application/PopupsService.java
  backend/pcloud-api/src/main/java/com/api/show/popups/infrastructure/PopupsCacheRepositoryImpl.java
  backend/pcloud-api/src/test/java/com/api/show/popups/application/PopupsServiceTest.java
  backend/pcloud-domain/src/main/java/com/domain/show/popups/cache/PopupsCacheRepository.java
  backend/pcloud-domain/src/main/java/com/domain/show/popups/domain/response/PopupsSpecificResponse.java
  backend/pcloud-domain/src/testFixtures/java/show/popups/infrastructure/FakePopupsCacheRepository.java
  backend/pcloud-infrastructure/src/main/java/com/infrastructure/config/RedisConfig.java
Labels: feat, BE

#61 feat: MSW 를 설정한다
  frontend/next.config.mjs
  frontend/package.json
  frontend/src/app/layout.tsx
  frontend/src/components/common/like-button/index.tsx
  frontend/src/components/common/list-card/index.tsx
  frontend/src/mocks/dummy.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/http.ts
  frontend/src/mocks/msw-Initializer.ts
  frontend/yarn.lock
Labels: feat, FE
