Repository sosow0212/2024-pop-cloud, pull requests merged in 2024-11, with the labels that each got.

#110 refactor: nav bar 디자인 수정하다
  frontend/src/app/shows/_components/filter-container.tsx
  frontend/src/components/mobile-header/index.tsx
  frontend/src/components/mobile-size-watcher/index.ts
  frontend/src/components/nav-bar/_components/nav-icon-button.tsx
  frontend/src/components/nav-bar/_components/nav-login-button.tsx
  frontend/src/components/nav-bar/_components/nav-logo.tsx
  frontend/src/components/nav-bar/_components/nav-menu.tsx
  frontend/src/components/nav-bar/index.tsx
  frontend/tailwind.config.ts
Labels: refactor, FE

#112 feat: 준비 중 페이지 제작하다
  frontend/src/app/error.tsx
  frontend/src/app/likes/page.tsx
  frontend/src/app/profile/page.tsx
  frontend/src/app/upcoming/page.tsx
Labels: feat, FE

#116 feat: 팝업/전시회등록 UI 제작
  frontend/package.json
  frontend/src/app/add-shows/_components/add-shows-form.tsx
  frontend/src/app/add-shows/_components/custom-tag-input.tsx
  frontend/src/app/add-shows/_components/description-input.tsx
  frontend/src/app/add-shows/_components/end-date-input.tsx
  frontend/src/app/add-shows/_components/facilities-selector.tsx
  frontend/src/app/add-shows/_components/fee-input.tsx
  frontend/src/app/add-shows/_components/image-input.tsx
  frontend/src/app/add-shows/_components/location-select.tsx
  frontend/src/app/add-shows/_components/open-time-input.tsx
  frontend/src/app/add-shows/_components/select-public-tags.tsx
  frontend/src/app/add-shows/_components/start-date-input.tsx
  frontend/src/app/add-shows/_components/title-input.tsx
  frontend/src/app/add-shows/constant/index.ts
  frontend/src/app/add-shows/page.tsx
  frontend/src/app/add-shows/types/index.ts
  frontend/src/app/add-shows/utils/date-utils.ts
  frontend/src/app/add-shows/validations/schema/index.tsx
  frontend/src/app/shows/page.tsx
  frontend/src/components/common/input/index.tsx
  frontend/src/components/ui/select.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/use-toggle.ts
  frontend/src/types/daum.d.ts
  frontend/yarn.lock
Labels: feat, FE

#118 feat: 팝업등록을 mock API 와 연동한다
  frontend/.gitignore
  frontend/src/api/create-popup.ts
  frontend/src/app/add-shows/_components/add-shows-form.tsx
  frontend/src/app/add-shows/validations/schema/index.tsx
  frontend/src/app/api/popups/route.ts
  frontend/src/app/shows/layout.tsx
  frontend/src/app/shows/page.tsx
  frontend/src/components/common/list-card/index.tsx
  frontend/src/mocks/db.service.ts
  frontend/src/mocks/handlers.ts
Labels: feat, FE

#121 feat: 상세페이지 api 연결을 한다
  frontend/src/api/get-shows.ts
  frontend/src/app/globals.css
  frontend/src/app/shows/[id]/_components/details-header.tsx
  frontend/src/app/shows/[id]/_components/details-info.tsx
  frontend/src/app/shows/[id]/_components/details-tabs.tsx
  frontend/src/app/shows/[id]/_components/details-tags.tsx
  frontend/src/app/shows/[id]/_components/relative-shows.tsx
  frontend/src/app/shows/[id]/layout.tsx
  frontend/src/app/shows/[id]/page.tsx
  frontend/src/app/shows/[id]/types/details.ts
  frontend/src/app/shows/hooks/use-shows-list.ts
  frontend/src/app/shows/page.tsx
  frontend/src/components/common/popup-card/index.tsx
  frontend/src/components/mobile-header/index.tsx
  frontend/src/components/nav-bar/_components/nav-logo.tsx
  frontend/src/components/nav-bar/index.tsx
  frontend/src/constants/shows.ts
  frontend/src/types/shows.ts
  frontend/tailwind.config.ts
Labels: feat, FE

#114 feat: footer 제작한다
  frontend/src/app/page.tsx
  frontend/src/app/upcoming/page.tsx
  frontend/src/components/footer/index.tsx
Labels: feat, FE

#125 feat: nav bar 디자인 변경하다
  frontend/src/app/(auth)/api/auth/login/oauth/kakao/page.tsx
  frontend/src/app/error.tsx
  frontend/src/components/main-container/index.tsx
  frontend/src/components/nav-bar/_components/nav-icon-button.tsx
  frontend/src/components/nav-bar/_components/nav-login-button.tsx
  frontend/src/components/nav-bar/_components/nav-logo.tsx
  frontend/src/components/nav-bar/_components/nav-menu.tsx
  frontend/src/components/nav-bar/_components/nav-size-button.tsx
  frontend/src/constants/index.ts
  frontend/src/constants/shrink-side-bar.ts
  frontend/src/mocks/handlers.ts
  frontend/src/store/index.ts
  frontend/src/store/use-shrink-nav-store.ts
Labels: feat, FE

#123 feat: 프론트엔드 도커를 설정한다
  frontend/.dockerignore
  frontend/Dockerfile
  frontend/docker-compose.yml
  frontend/next.config.mjs
  frontend/package.json
  frontend/src/api/custom-fetch.ts
  frontend/src/app/api/popups/route.ts
  frontend/src/app/layout.tsx
  frontend/src/mocks/browser.ts
  frontend/src/mocks/http.ts
  frontend/src/mocks/msw-Initializer.ts
  frontend/yarn.lock
Labels: infra, FE
