Repository sosow0212/2024-pop-cloud, pull requests merged in 2024-10, with the labels that each got.

#71 feat: Scheduler 중복 처리 작업을 제어하는 기능 추가
  .github/workflows/pcloud-backend-ci.yml
  backend/pcloud-batch/src/main/java/com/batch/job/show/exhibition/application/ExhibitionBatchPublisher.java
  backend/pcloud-batch/src/main/java/com/batch/job/show/popups/application/PopupsBatchPublisher.java
  backend/pcloud-common/src/main/java/com/common/annotation/BatchJob.java
  backend/pcloud-common/src/main/java/com/common/annotation/DistributionLock.java
  backend/pcloud-infrastructure/build.gradle
  backend/pcloud-infrastructure/src/main/java/com/infrastructure/config/RedisConfig.java
  backend/pcloud-infrastructure/src/main/java/com/infrastructure/exception/RetryException.java
  backend/pcloud-infrastructure/src/main/java/com/infrastructure/exception/RetryExceptionType.java
  backend/pcloud-infrastructure/src/main/java/com/infrastructure/lock/batch/aop/BatchLockAspect.java
  backend/pcloud-infrastructure/src/main/java/com/infrastructure/lock/batch/util/IdempotentManager.java
  backend/pcloud-infrastructure/src/main/java/com/infrastructure/lock/batch/util/RetryHandler.java
  backend/pcloud-infrastructure/src/main/java/com/infrastructure/lock/distribution/aop/DistributionLockAspect.java
Labels: feat, BE

#67 feat: 로그인 모달 제작한다
  frontend/.vscode/settings.json
  frontend/package.json
  frontend/public/icons/.gitkeep
  frontend/public/icons/google-icon.png
  frontend/public/icons/index.ts
  frontend/public/icons/kakao-talk-icon.png
  frontend/public/icons/naver-icon.png
  frontend/src/app/layout.tsx
  frontend/src/app/popups/page.tsx
  frontend/src/components/common/popup-card/index.tsx
  frontend/src/components/mobile-header/index.tsx
  frontend/src/components/modal/login-modal.tsx
  frontend/src/components/modal/modal-container.tsx
  frontend/src/components/nav-bar/_components/nav-login-button.tsx
  frontend/src/components/nav-bar/_components/nav-logo.tsx
  frontend/src/components/nav-bar/_components/nav-menu.tsx
  frontend/src/components/nav-bar/index.tsx
  frontend/src/components/ui/dialog.tsx
  frontend/src/components/ui/tooltip.tsx
  frontend/src/store/use-modal-store.ts
  frontend/yarn.lock
Labels: feat, FE

#70 feat: 상세페이지 ui를 제작한다
  frontend/.env.development
  frontend/package.json
  frontend/src/app/globals.css
  frontend/src/app/popups/[id]/layout.tsx
  frontend/src/app/popups/[id]/page.tsx
  frontend/src/components/common/carousel/index.tsx
  frontend/src/components/common/like-button/index.tsx
  frontend/src/components/common/popup-card/index.tsx
  frontend/src/components/details-page/details-header.tsx
  frontend/src/components/details-page/details-tabs.tsx
  frontend/src/components/details-page/details-tags.tsx
  frontend/src/components/details-page/review-form.tsx
  frontend/src/components/details-page/review.tsx
  frontend/src/components/mobile-header/index.tsx
  frontend/src/components/modal/login-modal.tsx
  frontend/src/components/nav-bar/_components/nav-login-button.tsx
  frontend/src/components/nav-bar/_components/nav-logo.tsx
  frontend/src/components/nav-bar/_components/nav-menu.tsx
  frontend/src/components/nav-bar/index.tsx
  frontend/src/components/ui/carousel.tsx
  frontend/src/components/ui/popover.tsx
  frontend/src/components/ui/tabs.tsx
  frontend/src/hooks/useToggle.ts
  frontend/src/mocks/dummy.ts
  frontend/src/mocks/handlers.ts
  frontend/tailwind.config.ts
  frontend/yarn.lock
Labels: feat, FE

#76 refactor: 쇼케이스 페이징 조회를 변경한다
  backend/pcloud-api/docs/asciidoc/exhibition.adoc
  backend/pcloud-api/docs/asciidoc/index.adoc
  backend/pcloud-api/docs/asciidoc/popups.adoc
  backend/pcloud-api/docs/asciidoc/show.adoc
  backend/pcloud-api/src/main/java/com/api/show/exhibition/application/ExhibitionQueryService.java
  backend/pcloud-api/src/main/java/com/api/show/exhibition/application/ExhibitionService.java
  backend/pcloud-api/src/main/java/com/api/show/exhibition/presentation/ExhibitionController.java
  backend/pcloud-api/src/main/java/com/api/show/popups/application/PopupsQueryService.java
  backend/pcloud-api/src/main/java/com/api/show/popups/infrastructure/PopupsRepositoryImpl.java
  backend/pcloud-api/src/main/java/com/api/show/popups/presentation/PopupsController.java
  backend/pcloud-api/src/main/java/com/api/show/show/application/ShowQueryService.java
  backend/pcloud-api/src/main/java/com/api/show/show/application/dto/ShowPagingFilterRequest.java
  backend/pcloud-api/src/main/java/com/api/show/show/infrastructure/ShowRepositoryImpl.java
  backend/pcloud-api/src/main/java/com/api/show/show/presentation/ShowController.java
  backend/pcloud-api/src/test/java/com/api/helper/MockBeanInjection.java
  backend/pcloud-api/src/test/java/com/api/show/exhibition/application/ExhibitionQueryServiceTest.java
  backend/pcloud-api/src/test/java/com/api/show/exhibition/presentation/ExhibitionControllerAcceptanceTest.java
  backend/pcloud-api/src/test/java/com/api/show/exhibition/presentation/ExhibitionControllerAcceptanceTestFixture.java
  backend/pcloud-api/src/test/java/com/api/show/exhibition/presentation/ExhibitionControllerWebMvcTest.java
  backend/pcloud-api/src/test/java/com/api/show/popups/presentation/PopupsControllerAcceptanceFixture.java
  backend/pcloud-api/src/test/java/com/api/show/popups/presentation/PopupsControllerAcceptanceTest.java
  backend/pcloud-api/src/test/java/com/api/show/popups/presentation/PopupsControllerWebMvcTest.java
  backend/pcloud-api/src/test/java/com/api/show/show/application/ShowQueryServiceTest.java
  backend/pcloud-api/src/test/java/com/api/show/show/presentation/ShowControllerAcceptanceFixture.java
  backend/pcloud-api/src/test/java/com/api/show/show/presentation/ShowControllerAcceptanceTest.java
  backend/pcloud-api/src/test/java/com/api/show/show/presentation/ShowControllerWebMvcTest.java
  backend/pcloud-domain/src/main/java/com/domain/show/exhibition/domain/ExhibitionRepository.java
  backend/pcloud-domain/src/main/java/com/domain/show/exhibition/domain/dto/ExhibitionSimpleResponse.java
  backend/pcloud-domain/src/main/java/com/domain/show/exhibition/infrastructure/ExhibitionQueryRepository.java
  backend/pcloud-domain/src/main/java/com/domain/show/exhibition/infrastructure/ExhibitionRepositoryImpl.java
  backend/pcloud-domain/src/main/java/com/domain/show/popups/domain/PopupsRepository.java
  backend/pcloud-domain/src/main/java/com/domain/show/popups/domain/response/PopupsSimpleResponse.java
  backend/pcloud-domain/src/main/java/com/domain/show/popups/infrastructure/PopupsQueryRepository.java
  backend/pcloud-domain/src/main/java/com/domain/show/show/domain/ShowRepository.java
  backend/pcloud-domain/src/main/java/com/domain/show/show/domain/dto/ShowSimpleResponse.java
  backend/pcloud-domain/src/main/java/com/domain/show/show/infrastructure/ShowQueryRepository.java
  backend/pcloud-domain/src/test/java/com/domain/show/exhibition/infrastructure/ExhibitionQueryRepositoryTest.java
  backend/pcloud-domain/src/test/java/com/domain/show/popups/infrastructure/PopupsQueryRepositoryTest.java
  backend/pcloud-domain/src/test/java/com/domain/show/show/infrastructure/ShowQueryRepositoryTest.java
  backend/pcloud-domain/src/testFixtures/java/show/exhibition/infrasturcture/ExhibitionFakeRepository.java
  backend/pcloud-domain/src/testFixtures/java/show/popups/infrastructure/FakePopupsRepository.java
  backend/pcloud-domain/src/testFixtures/java/show/show/domain/dto/ShowSimpleResponseFixture.java
Labels: refactor, BE

#74 Fix: nav bar 마진 문제 해결한다
  frontend/package.json
  frontend/src/app/layout.tsx
  frontend/src/components/main-container/index.tsx
  frontend/src/components/mobile-header/index.tsx
  frontend/src/components/modal/login-modal.tsx
  frontend/src/components/nav-bar/_components/nav-logo.tsx
Labels: fix, FE

#68 feat: 공통 컴포넌트 지도를 구현한다
  frontend/.env.development
  frontend/.storybook/preview-head.html
  frontend/.vscode/settings.json
  frontend/package.json
  frontend/public/images/map/bookmark-marker.png
  frontend/public/images/map/current-marker.png
  frontend/public/images/map/place-marker.png
  frontend/src/app/layout.tsx
  frontend/src/components/map/index.stories.tsx
  frontend/src/components/map/index.tsx
  frontend/src/components/map/map-container.tsx
  frontend/src/components/map/map-marker.tsx
  frontend/src/components/map/map-static.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/use-init-map-center.ts
  frontend/src/types/map.d.ts
  frontend/tsconfig.json
  frontend/yarn.lock
Labels: feat, TODO, FE

#83 feat: 팝업카드 슬라이드 제작한다
  frontend/src/app/page.tsx
  frontend/src/components/common/popup-card/index.tsx
  frontend/src/components/common/popup-slide/index.tsx
  frontend/src/components/common/popup-slide/mockData.ts
Labels: feat, FE

#79 feat: 토스트 / 링크 기능 제작
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/popups/[id]/layout.tsx
  frontend/src/components/common/index.ts
  frontend/src/components/common/toast/index.stories.tsx
  frontend/src/components/common/toast/index.tsx
  frontend/src/components/details-page/details-header.tsx
  frontend/src/components/details-page/details-tags.tsx
  frontend/src/components/ui/carousel.tsx
  frontend/src/hooks/useToggle.ts
  frontend/src/store/.gitkeep
  frontend/src/store/use-toast-store.ts
  frontend/tailwind.config.ts
Labels: feat, FE

#80 feat: 리스트 페이지 제작
  frontend/package.json
  frontend/src/api/get-shows.ts
  frontend/src/app/layout.tsx
  frontend/src/app/popups/page.tsx
  frontend/src/app/shows/_components/check-list.tsx
  frontend/src/app/shows/_components/date-ficker.tsx
  frontend/src/app/shows/_components/filter-acordian.tsx
  frontend/src/app/shows/_components/filter-sidebar.tsx
  frontend/src/app/shows/_components/mobile-filter.tsx
  frontend/src/app/shows/_components/region-select.tsx
  frontend/src/app/shows/_components/search-input.tsx
  frontend/src/app/shows/_components/show-lists.tsx
  frontend/src/app/shows/_components/tag-button-list.tsx
  frontend/src/app/shows/layout.tsx
  frontend/src/app/shows/page.tsx
  frontend/src/app/shows/types/index.ts
  frontend/src/components/common/list-card/index.stories.tsx
  frontend/src/components/common/list-card/index.tsx
  frontend/src/components/nav-bar/_components/nav-menu.tsx
  frontend/src/components/ui/accordion.tsx
  frontend/src/components/ui/checkbox.tsx
  frontend/src/mocks/dummy.ts
  frontend/src/mocks/handlers.ts
  frontend/src/mocks/index.ts
  frontend/src/mocks/server.ts
  frontend/src/provider/query-client-provider.tsx
  frontend/tailwind.config.ts
  frontend/yarn.lock
Labels: feat, FE

#90 feat: 액션 빌드시간을 단축한다
  .github/workflows/storybook.yml
  frontend/src/app/layout.tsx
Labels: feat, FE

#87 Feat: 카카오 소셜 로그인 연결한다
  frontend/.env.development
  frontend/.gitignore
  frontend/src/api/.gitkeep
  frontend/src/api/auth/kakao.ts
  frontend/src/api/custom-fetch.ts
  frontend/src/app/(auth)/api/auth/login/oauth/kakao/page.tsx
  frontend/src/app/error.tsx
  frontend/src/app/popups/[id]/page.tsx
  frontend/src/components/common/loading/square-spinner.tsx
  frontend/src/components/common/toast/index.tsx
  frontend/src/components/modal/login-modal.tsx
  frontend/src/components/nav-bar/_components/nav-menu.tsx
  frontend/src/components/nav-bar/index.tsx
  frontend/src/custom-error/api-error.ts
  frontend/src/custom-error/custom-error.ts
  frontend/src/custom-error/index.ts
  frontend/src/mocks/handlers.ts
  frontend/src/store/use-user-store.ts
  frontend/src/utils/browser-cookies.ts
  frontend/src/utils/next-cookie.ts
  frontend/tailwind.config.ts
Labels: feat, FE

#88 feat: 검색기능 구현 및 무한스크롤을 구현한다
  frontend/src/api/get-shows.ts
  frontend/src/app/layout.tsx
  frontend/src/app/shows/_components/check-list.tsx
  frontend/src/app/shows/_components/filter-acordian.tsx
  frontend/src/app/shows/_components/mobile-filter.tsx
  frontend/src/app/shows/_components/region-select.tsx
  frontend/src/app/shows/_components/search-input.tsx
  frontend/src/app/shows/_components/show-lists.tsx
  frontend/src/app/shows/_components/spinner.tsx
  frontend/src/app/shows/_components/tag-button-list.tsx
  frontend/src/app/shows/hooks/use-shows-list.ts
  frontend/src/app/shows/layout.tsx
  frontend/src/app/shows/page.tsx
  frontend/src/app/shows/types/index.ts
  frontend/src/components/common/list-card/index.tsx
  frontend/src/mocks/dummy.ts
  frontend/src/mocks/handlers.ts
  frontend/src/stories/.gitkeep
  frontend/src/types/.gitkeep
  frontend/tailwind.config.ts
Labels: feat, FE

#96 feat: 지도 페이지 사이드 바 넓이 줄이다
  README.md
  frontend/src/components/common/toast/index.tsx
  frontend/src/components/main-container/index.tsx
  frontend/src/components/nav-bar/_components/nav-icon-button.tsx
  frontend/src/components/nav-bar/_components/nav-login-button.tsx
  frontend/src/components/nav-bar/_components/nav-logo.tsx
  frontend/src/components/nav-bar/_components/nav-menu.tsx
  frontend/src/constants/.gitkeep
  frontend/src/constants/index.ts
  frontend/src/constants/shrink-side-bar.ts
Labels: feat, FE

#93 feat: 상세페이지에 지도컴포넌트를 추가한다
  frontend/src/app/popups/[id]/layout.tsx
  frontend/src/app/shows/[id]/_components/details-header.tsx
  frontend/src/app/shows/[id]/_components/details-tabs.tsx
  frontend/src/app/shows/[id]/_components/details-tags.tsx
  frontend/src/app/shows/[id]/_components/review-form.tsx
  frontend/src/app/shows/[id]/_components/review.tsx
  frontend/src/app/shows/[id]/layout.tsx
  frontend/src/app/shows/[id]/page.tsx
  frontend/src/components/common/list-card/index.tsx
  frontend/src/components/map/map-marker.tsx
Labels: feat, FE

#94 feat: 지도 페이지를 제작한다.
  frontend/package.json
  frontend/public/images/map/bookmark-marker.png
  frontend/public/images/map/current-marker.png
  frontend/public/images/map/exhibition-marker.png
  frontend/public/images/map/popups-marker.png
  frontend/src/app/globals.css
  frontend/src/app/layout.tsx
  frontend/src/app/map/_components/map-recommendation.tsx
  frontend/src/app/map/_components/map-search.tsx
  frontend/src/app/map/_components/map-side-button.tsx
  frontend/src/app/map/_components/map-side-item.tsx
  frontend/src/app/map/_components/map-sidebar.tsx
  frontend/src/app/map/layout.tsx
  frontend/src/app/map/page.tsx
  frontend/src/components/common/list-card/index.tsx
  frontend/src/components/common/popup-card/index.tsx
  frontend/src/components/map/index.stories.tsx
  frontend/src/components/map/index.tsx
  frontend/src/components/map/map-container.tsx
  frontend/src/components/map/map-marker.tsx
  frontend/src/components/map/map-static.tsx
  frontend/src/components/modal/index.ts
  frontend/src/components/modal/modal-container.tsx
  frontend/src/components/modal/recommendation-modal.tsx
  frontend/src/components/ui/dialog.tsx
  frontend/src/components/ui/drawer.tsx
  frontend/src/hooks/index.ts
  frontend/src/hooks/use-init-map-center.ts
  frontend/src/hooks/use-map-search.ts
  frontend/src/hooks/use-map-state.ts
  frontend/src/provider/modal-provider.tsx
  frontend/src/provider/query-client-provider.tsx
  frontend/src/store/use-modal-store.ts
  frontend/src/types/map.d.ts
  frontend/tailwind.config.ts
  frontend/yarn.lock
Labels: feat, FE

#100 feat: 팝업 전시 필터 및 브랜드 태그 보여주기
  frontend/package.json
  frontend/src/api/get-shows.ts
  frontend/src/app/shows/_components/search-input.tsx
  frontend/src/app/shows/_components/selected-tags.tsx
  frontend/src/app/shows/_components/show-lists.tsx
  frontend/src/app/shows/_components/shows-type-filter.tsx
  frontend/src/app/shows/layout.tsx
  frontend/src/app/shows/page.tsx
  frontend/src/components/ui/badge.tsx
  frontend/src/components/ui/dropdown-menu.tsx
  frontend/yarn.lock
Labels: feat, FE

#108 refactor: 필터 사이드바 리팩토링한다
  frontend/src/app/shows/_components/filter-container.tsx
  frontend/src/app/shows/_components/filter-sidebar.tsx
  frontend/src/app/shows/_components/filter-wrapper.tsx
  frontend/src/app/shows/_components/selected-tags.tsx
  frontend/src/app/shows/layout.tsx
  frontend/src/app/shows/page.tsx
  frontend/src/components/map/map-marker.tsx
  frontend/src/components/nav-bar/_components/nav-menu.tsx
Labels: refactor, FE
